# Generated by Django 5.0.1 on 2024-01-27 22:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipeproduct",
            old_name="product_id",
            new_name="product",
        ),
        migrations.RenameField(
            model_name="recipeproduct",
            old_name="recipe_id",
            new_name="recipe",
        ),
    ]
